### ISSUE TITLE
NotAllowedError: The operation either timed out or was not allowed

### ISSUE THREAD

**Issue by gusdgg** [uru-card/uru-card#13]
Hi,

Amazing project, congratulations. I was using just a simple Wroom 32 development board to test the FIDO2 authentication protocol with BLE. Using chrome on windows 10 gives the following error in webauthn.bin.coffee and also in webauthn.me:

_NotAllowedError: The operation either timed out or was not allowed. See: https://www.w3.org/TR/webauthn-2/#sctn-privacy-considerations-client._

I can see the msgs flowing in the console (GetInfo, MakeCredential, Hash, Private Key, Signature, Encoded signature and Responding with payload) but the browser gives the NotAllowedError.

Thank you and regards.

**Comment by gusdgg** [comment]
I've tested [this version](https://github.com/uru-card/uru-card/tree/47ffb1ecb00e515479980240f7ed27d2fee52c1e) with esp32 Wroom and worked!

Thanks.

**Comment by snakeye** [comment]
I'm a little bit late with the answer.

Thank you for digging into it! I'll try to find time to update the latest master with the fix.
