### ISSUE TITLE
Cryptographic Chip is not setup?

### ISSUE THREAD

**Issue by staberas** [uru-card/uru-card#8]
Hi, i was playing around with the simple hardware test of the uru Card and trying to test its various abilities. While trying to generate random numbers using the SparkFun_ATECCX08a_Arduino_Library i found out that the chip is not setup(not locked configuration) and the random numbers given out where the same every time. Looking at this library i see you implemented code for configuring the chip but it apparantly wasnt in my case. Could this be the reason FIDO is broken right now?

**Comment by snakeye** [comment]
Hello!

That's quite curious - the security chip locking is implemented and should be called if needed - https://github.com/uru-card/uru-card/blob/master/src/main.cpp#L35. Your previous issue with U2F (#6) is not related to this.

How do you test the implementation? Some website or tool?

**Comment by staberas** [comment]
I used your hardware test (reflashed the URU card you send me) https://github.com/uru-card/uru-card-hardware-test as a base and then 
started playing around with the cryptographic chip RNG ( https://github.com/sparkfun/SparkFun_ATECCX08a_Arduino_Library/blob/master/examples/Example5_Random/Example5_Random.ino )
When im calling the:
```
   // print a random number between 0 and 100
  long myRandomNumber = atecc.random(1,80);
  Serial.print("Random number: ");
  Serial.println(myRandomNumber);
```
i would always get  39 everytime

Then i added the line
`printInfo(); // see function below for library calls and data handling
`
and it printed **not locked**

**Comment by snakeye** [comment]
The hardware test neither locks nor configures the chip. It just checks if the chip is available.

You can simply flash the example configuration sketch https://github.com/sparkfun/SparkFun_ATECCX08a_Arduino_Library/blob/master/examples/Example1_Configuration/Example1_Configuration.ino to execute the configuration procedure and then proceed with other tests.

**Comment by staberas** [comment]
ah yes did that already, i was simply confused it wasnt locked from before. Just reporting it, in case it was a bug/mistake   :)

**Comment by snakeye** [comment]
I see. From the code perspective, it looks like the chip should be configured on the first start and to confirm the bug I need to resolder my device with the new chip :) Will do that, but can't provide any ETA. Closing the issue for now.
